# docker-compose.override.yml
version: '3.8'

services:
  signin-bot:
    environment:
      - Discord__TargetChannelId=1369947198800003072
      - Discord__Guilds__0__GuildId=1364185117182005308
      - Discord__Guilds__0__AdminRoleId=1364526514665816084
      - Discord__Guilds__0__GuildName=Erik Discord
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Discord=Debug
      - Logging__LogLevel__Discord.Net=Debug
      - Logging__LogLevel__MorningSignInBot=Debug
      - Database__Path=/app/data/signins.db
    volumes:
      - C:\Users\erikg\Documents\Dev\Signup bot\MorningSignInBot/appsettings.json:/app/appsettings.json:ro
      - C:\Users\erikg\Documents\Dev\Signup bot\MorningSignInBot/data:/app/data:rw
      - bot-logs:/app/logs:rw
    user: "1000:1000"

volumes:
  bot-logs:
