version: '3.8'

services:
  signin-bot:
    image: ${REGISTRY:-mylocal}/morning-signin-bot:${TAG:-latest}
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - bot-data:/app/data
      - bot-logs:/app/Logs
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT:-Production}
      - TZ=${TZ:-Europe/Oslo}
      - Discord__Token=${DISCORD_TOKEN:-file:///run/secrets/discord_bot_token}
      - Discord__RegisterCommandsGlobally=true
      - Discord__TargetChannelId=${DISCORD_CHANNEL_ID}
      - Discord__Guilds__0__GuildId=${DISCORD_GUILD_ID}
      - Discord__Guilds__0__AdminRoleId=${DISCORD_ADMIN_ROLE_ID}
      - Discord__Guilds__0__GuildName=${DISCORD_GUILD_NAME:-Your Server Name}
      - Discord__SignInHour=${SIGNIN_HOUR:-8}
      - Discord__SignInMinute=${SIGNIN_MINUTE:-0}
      - Logging__LogLevel__Default=${Logging__LogLevel__Default:-Information}
      - Logging__LogLevel__MorningSignInBot=${Logging__LogLevel__MorningSignInBot:-Information}
      - Logging__LogLevel__Microsoft=${Logging__LogLevel__Microsoft:-Warning}
    secrets:
      - source: discord_bot_token
        target: /run/secrets/discord_bot_token 
        mode: 0444
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3 
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-data:
    driver: local
  bot-logs:
    driver: local

secrets:
  discord_bot_token:
    external: true
