version: '3.8'
services:
  signin-bot:
    environment:
      - Discord__TargetChannelId=1369947198800003072
      - Discord__Guilds__0__GuildId=1364185117182005308
      - Discord__Guilds__0__AdminRoleId=1364526514665816084
      - Discord__Guilds__0__GuildName=Erik Discord
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Discord=Trace
      - Logging__LogLevel__Discord.Net.WebSocket=Trace
      - Logging__LogLevel__Discord.Net.WebSocket.DiscordSocketClient=Trace
      - Logging__LogLevel__Discord.Net.Rest=Trace
      - Logging__LogLevel__Discord.Net.Gateway=Trace
      - Logging__LogLevel__MorningSignInBot=Trace
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - C:\Users\erikg\Documents\Dev\Signup bot\MorningSignInBot/appsettings.json:/app/appsettings.json:ro
      - bot-data:/app/data
      - bot-logs:/app/logs
volumes:
  bot-data:
  bot-logs: